# Generated by Django 2.0.5 on 2018-06-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='train.jpg', upload_to=''),
        ),
    ]
